### ISSUE TITLE
Subscribers functionality no longer available in Settings > Labs

### ISSUE THREAD

**Issue by remjx** [bironthemes/biron-ghost-theme#11]
I do not see the Subscribers option available in Labs. The Subscribers functionality of theme looks like it is obsolete with the latest version of Ghost that supports Members.

https://bironthemes.com/docs/biron-ghost/#36-subscribers

**Comment by brightthemes** [comment]
With Ghost 3.0 the Subscribers option is not available anymore. It's basically part of the Members feature. This theme is compatible with Ghost 3.0 but the Membership feature is not implemented yet. I will update the documentation (that part is not valid for Ghost 3.0.
