### ISSUE TITLE
Any plans to upgrade to Ghost V2?

### ISSUE THREAD

**Issue by pascalandy** [bironthemes/biron-ghost-theme#6]
It should be fairly easy :)

If it help, look at those commit https://github.com/firepress-org/FirePress_Vapor/commits/master

Cheers!

**Comment by brightthemes** [comment]
Hi Andy, it is already in plan to do it, but since we have other themes that had priority we didn't get to it yet, should be done next week!

**Comment by pascalandy** [comment]
Thank you!

**Comment by brightthemes** [comment]
Done!
