### ISSUE TITLE
The pages are not rendering as it should 

### ISSUE THREAD

**Issue by pascalandy** [bironthemes/biron-ghost-theme#8]
See

### post

![screen shot 2018-10-21 at 7 15 02 pm](https://user-images.githubusercontent.com/6694151/47273639-e5494e80-d565-11e8-89f4-5ee28237f810.jpg)

### page

![screen shot 2018-10-21 at 7 15 10 pm](https://user-images.githubusercontent.com/6694151/47273640-e8dcd580-d565-11e8-825e-d24cfe4d1b7b.jpg)

**Comment by norberthnd** [comment]
Fixed that.
